os: osx

language: scala
scala:
  - 2.13.1

jdk: openjdk11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

stages:
  - test

jobs:
  include:
    - stage: test
      name: "Run all unit tests"
      script: "sbt test"
